export const REQUEST_GET_MOVIE_DETAIL = 'REQUEST_GET_MOVIE_DETAIL'
export const REQUEST_LOADING_MOVIE_DETAIL = 'REQUEST_LOADING_MOVIE_DETAIL'
export const REQUEST_ERROR_MOVIE_DETAIL = 'REQUEST_ERROR_MOVIE_DETAIL'